using Content.Shared._DV.CCVars;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client._DV.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class DeltaTab : Control
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    private const int LayoutUs = 0;
    private const int LayoutQwertz = 1;
    private const int LayoutAzerty = 2;

    private string _selectedKeyboardLayout = "us";

    public DeltaTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        DisableFiltersCheckBox.OnToggled += OnCheckBoxToggled;
        DisableFiltersCheckBox.Pressed = _cfg.GetCVar(DCCVars.NoVisionFilters);

        KeyboardLayoutOption.AddItem(Loc.GetString("ui-options-programmable-computer-layout-us"), LayoutUs);
        KeyboardLayoutOption.AddItem(Loc.GetString("ui-options-programmable-computer-layout-qwertz"), LayoutQwertz);
        KeyboardLayoutOption.AddItem(Loc.GetString("ui-options-programmable-computer-layout-azerty"), LayoutAzerty);

        _selectedKeyboardLayout = NormalizeLayout(_cfg.GetCVar(CCVars.ProgrammableComputerKeyboardLayout));
        KeyboardLayoutOption.SelectId(LayoutToId(_selectedKeyboardLayout));
        KeyboardLayoutOption.OnItemSelected += OnKeyboardLayoutSelected;

        ApplyButton.OnPressed += OnApplyButtonPressed;
        UpdateApplyButton();
    }

    private void OnKeyboardLayoutSelected(OptionButton.ItemSelectedEventArgs args)
    {
        KeyboardLayoutOption.SelectId(args.Id);
        _selectedKeyboardLayout = args.Id switch
        {
            LayoutQwertz => "qwertz",
            LayoutAzerty => "azerty",
            _ => "us",
        };

        UpdateApplyButton();
    }

    private void OnCheckBoxToggled(BaseButton.ButtonToggledEventArgs args)
    {
        UpdateApplyButton();
    }

    private void OnApplyButtonPressed(BaseButton.ButtonEventArgs args)
    {
        _cfg.SetCVar(DCCVars.NoVisionFilters, DisableFiltersCheckBox.Pressed);
        _cfg.SetCVar(CCVars.ProgrammableComputerKeyboardLayout, _selectedKeyboardLayout);

        _cfg.SaveToFile();
        UpdateApplyButton();
    }

    private void UpdateApplyButton()
    {
        var isNoVisionFiltersSame = DisableFiltersCheckBox.Pressed == _cfg.GetCVar(DCCVars.NoVisionFilters);
        var isKeyboardLayoutSame = _selectedKeyboardLayout == NormalizeLayout(_cfg.GetCVar(CCVars.ProgrammableComputerKeyboardLayout));

        ApplyButton.Disabled = isNoVisionFiltersSame && isKeyboardLayoutSame;
    }

    private static int LayoutToId(string layout)
    {
        return layout switch
        {
            "qwertz" => LayoutQwertz,
            "azerty" => LayoutAzerty,
            _ => LayoutUs,
        };
    }

    private static string NormalizeLayout(string layout)
    {
        return layout.ToLowerInvariant() switch
        {
            "qwertz" => "qwertz",
            "azerty" => "azerty",
            _ => "us",
        };
    }
}
