using Content.Shared._DV.CCVars;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using System;
using System.IO;

namespace Content.Client._DV.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class DeltaTab : Control
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    private const int LayoutUs = 0;
    private const int LayoutQwertz = 1;
    private const int LayoutAzerty = 2;

    private string _selectedKeyboardLayout = "us";

    public DeltaTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        DisableFiltersCheckBox.OnToggled += OnCheckBoxToggled;
        DisableFiltersCheckBox.Pressed = _cfg.GetCVar(DCCVars.NoVisionFilters);

        KeyboardLayoutOption.AddItem(Loc.GetString("ui-options-programmable-computer-layout-us"), LayoutUs);
        KeyboardLayoutOption.AddItem(Loc.GetString("ui-options-programmable-computer-layout-qwertz"), LayoutQwertz);
        KeyboardLayoutOption.AddItem(Loc.GetString("ui-options-programmable-computer-layout-azerty"), LayoutAzerty);

        _selectedKeyboardLayout = NormalizeLayout(_cfg.GetCVar(CCVars.ProgrammableComputerKeyboardLayout));
        KeyboardLayoutOption.SelectId(LayoutToId(_selectedKeyboardLayout));
        KeyboardLayoutOption.OnItemSelected += OnKeyboardLayoutSelected;

        ApplyButton.OnPressed += OnApplyButtonPressed;
        SaveDefaultWindowSizeButton.OnPressed += OnSaveDefaultWindowSizePressed;
        ResetWindowSizesButton.OnPressed += OnResetWindowSizesPressed;
        UpdateApplyButton();
    }

    private void OnKeyboardLayoutSelected(OptionButton.ItemSelectedEventArgs args)
    {
        KeyboardLayoutOption.SelectId(args.Id);
        _selectedKeyboardLayout = args.Id switch
        {
            LayoutQwertz => "qwertz",
            LayoutAzerty => "azerty",
            _ => "us",
        };

        UpdateApplyButton();
    }

    private void OnCheckBoxToggled(BaseButton.ButtonToggledEventArgs args)
    {
        UpdateApplyButton();
    }

    private void OnApplyButtonPressed(BaseButton.ButtonEventArgs args)
    {
        _cfg.SetCVar(DCCVars.NoVisionFilters, DisableFiltersCheckBox.Pressed);
        _cfg.SetCVar(CCVars.ProgrammableComputerKeyboardLayout, _selectedKeyboardLayout);

        _cfg.SaveToFile();
        UpdateApplyButton();
    }

    private void UpdateApplyButton()
    {
        var isNoVisionFiltersSame = DisableFiltersCheckBox.Pressed == _cfg.GetCVar(DCCVars.NoVisionFilters);
        var isKeyboardLayoutSame = _selectedKeyboardLayout == NormalizeLayout(_cfg.GetCVar(CCVars.ProgrammableComputerKeyboardLayout));

        ApplyButton.Disabled = isNoVisionFiltersSame && isKeyboardLayoutSame;
    }

    private static int LayoutToId(string layout)
    {
        return layout switch
        {
            "qwertz" => LayoutQwertz,
            "azerty" => LayoutAzerty,
            _ => LayoutUs,
        };
    }

    private static string NormalizeLayout(string layout)
    {
        return layout.ToLowerInvariant() switch
        {
            "qwertz" => "qwertz",
            "azerty" => "azerty",
            _ => "us",
        };
    }

    private void OnSaveDefaultWindowSizePressed(BaseButton.ButtonEventArgs args)
    {
        try
        {
            var sizeData = LoadWindowSizes();
            if (sizeData.Count > 0)
            {
                // Average all saved window sizes
                var avgWidth = 0f;
                var avgHeight = 0f;
                foreach (var size in sizeData.Values)
                {
                    avgWidth += size.Width;
                    avgHeight += size.Height;
                }
                avgWidth /= sizeData.Count;
                avgHeight /= sizeData.Count;
                
                var sizeStr = $"{avgWidth:F0},{avgHeight:F0}";
                _cfg.SetCVar(CCVars.ProgrammableComputerDefaultWindowSize, sizeStr);
                _cfg.SaveToFile();
            }
        }
        catch
        {
            // Silently fail
        }
    }

    private void OnResetWindowSizesPressed(BaseButton.ButtonEventArgs args)
    {
        try
        {
            var settingsPath = GetWindowSizesPath();
            if (File.Exists(settingsPath))
            {
                File.Delete(settingsPath);
            }
            _cfg.SetCVar(CCVars.ProgrammableComputerDefaultWindowSize, "");
            _cfg.SaveToFile();
        }
        catch
        {
            // Silently fail
        }
    }

    private static Dictionary<string, SizeData> LoadWindowSizes()
    {
        var settingsPath = GetWindowSizesPath();
        if (!File.Exists(settingsPath))
            return new Dictionary<string, SizeData>();

        try
        {
            var json = File.ReadAllText(settingsPath);
            var dict = System.Text.Json.JsonSerializer.Deserialize<Dictionary<string, SizeData>>(json);
            return dict ?? new Dictionary<string, SizeData>();
        }
        catch
        {
            return new Dictionary<string, SizeData>();
        }
    }

    private static string GetWindowSizesPath()
    {
        var baseDir = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
        return Path.Combine(baseDir, "SpaceStation14", "programmable_computer_window_sizes.json");
    }

    private record SizeData
    {
        public float Width { get; set; }
        public float Height { get; set; }
    }
}
