using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared.ProgrammableComputer;
using Robust.Client.Input;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Keyboard = Robust.Client.Input.Keyboard;

namespace Content.Client.ProgrammableComputer;

[GenerateTypedNameReferences]
public sealed partial class ProgrammableComputerWindow : FancyWindow, IComputerWindow<ProgrammableComputerBoundUserInterfaceState>
{
    [Dependency] private readonly IInputManager _input = default!;
    private const string LockedPrefix = "[LOCKED]";
    private const string UnlockedPrefix = "[UNLOCKED]";

    private ComputerBoundUserInterfaceBase? _bui;
    private bool _inputLocked;
    private string _baseTitle = string.Empty;

    public ProgrammableComputerWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _baseTitle = Title ?? string.Empty;

        TerminalSurface.KeyboardFocusOnClick = true;
        TerminalSurface.OnTerminalClicked += OnTerminalClicked;
        TerminalSurface.OnTerminalTextEntered += OnTerminalTextEntered;
        _input.FirstChanceOnKeyEvent += OnFirstChanceKeyEvent;
        StartButton.OnPressed += _ => _bui?.SendMessage(new ProgrammableComputerPowerActionMessage(ProgrammableComputerPowerAction.Start));
        ShutdownButton.OnPressed += _ => _bui?.SendMessage(new ProgrammableComputerPowerActionMessage(ProgrammableComputerPowerAction.Shutdown));
        RebootButton.OnPressed += _ => _bui?.SendMessage(new ProgrammableComputerPowerActionMessage(ProgrammableComputerPowerAction.Reboot));

        SetInputLocked(false);

        OnClose += () =>
        {
            _input.FirstChanceOnKeyEvent -= OnFirstChanceKeyEvent;
            TerminalSurface.OnTerminalClicked -= OnTerminalClicked;
            TerminalSurface.OnTerminalTextEntered -= OnTerminalTextEntered;
        };
    }

    public void SetupComputerWindow(ComputerBoundUserInterfaceBase cb)
    {
        _bui = cb;
        SetInputLocked(false);
    }

    public void UpdateState(ProgrammableComputerBoundUserInterfaceState state)
    {
        TerminalSurface.UpdateTerminal(state.TerminalCells, state.CursorX, state.CursorY, state.CursorBlink);
        StartButton.Disabled = state.PoweredOn || state.Booting;
        ShutdownButton.Disabled = !state.PoweredOn;
        RebootButton.Disabled = !state.PoweredOn;
        PowerStateLabel.Text = state.Booting
            ? "Power: BOOTING"
            : state.PoweredOn
                ? "Power: ON"
                : "Power: OFF";
    }

    protected override void ExitedTree()
    {
        SetInputLocked(false);
        base.ExitedTree();
        _input.FirstChanceOnKeyEvent -= OnFirstChanceKeyEvent;
        TerminalSurface.OnTerminalClicked -= OnTerminalClicked;
        TerminalSurface.OnTerminalTextEntered -= OnTerminalTextEntered;
    }

    protected override void ControlFocusExited()
    {
        base.ControlFocusExited();
        SetInputLocked(false);
    }

    private void OnTerminalClicked()
    {
        SetInputLocked(true);
    }

    private void OnTerminalTextEntered(string text)
    {
        if (_bui == null || !_inputLocked || string.IsNullOrEmpty(text))
            return;

        _bui.SendMessage(new ProgrammableComputerTextInputMessage(text));
    }

    private void SetInputLocked(bool locked)
    {
        _inputLocked = locked;

        if (locked)
            TerminalSurface.GrabKeyboardFocus();
        else
            TerminalSurface.ReleaseKeyboardFocus();

        Title = locked ? $"{LockedPrefix} {_baseTitle}" : $"{UnlockedPrefix} {_baseTitle}";
    }

    private void OnFirstChanceKeyEvent(KeyEventArgs keyEvent, KeyEventType type)
    {
        if (_bui == null || !_inputLocked || !TerminalSurface.HasKeyboardFocus())
            return;

        if (type == KeyEventType.Down && keyEvent.Key == Keyboard.Key.Escape)
        {
            SetInputLocked(false);
            keyEvent.Handle();
            return;
        }

        if (type == KeyEventType.Repeat)
        {
            keyEvent.Handle();
            return;
        }

        switch (type)
        {
            case KeyEventType.Down:
                _bui.SendMessage(new ProgrammableComputerKeyMessage(
                    (int) keyEvent.Key,
                    true,
                    false,
                    keyEvent.Control,
                    keyEvent.Alt,
                    keyEvent.Shift,
                    keyEvent.System));
                break;
            case KeyEventType.Up:
                if (keyEvent.Key is not (Keyboard.Key.Control or Keyboard.Key.Shift or Keyboard.Key.Alt or Keyboard.Key.LSystem or Keyboard.Key.RSystem))
                {
                    keyEvent.Handle();
                    return;
                }

                _bui.SendMessage(new ProgrammableComputerKeyMessage(
                    (int) keyEvent.Key,
                    false,
                    false,
                    keyEvent.Control,
                    keyEvent.Alt,
                    keyEvent.Shift,
                    keyEvent.System));
                break;
        }

        keyEvent.Handle();
    }
}
