using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared.ProgrammableComputer;
using JetBrains.Annotations;
using Robust.Client.UserInterface;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;

namespace Content.Client.ProgrammableComputer;

[GenerateTypedNameReferences]
public sealed partial class ProgrammableComputerFileManagerWindow : FancyWindow
{
    [Dependency] private readonly IFileDialogManager _dialogs = default!;

    private ComputerBoundUserInterfaceBase? _bui;
    private readonly List<string> _fileNames = new();
    private int _selectedIndex = -1;
    private bool _isUploadDialogOpen;
    private string? _pendingDownloadFileName;
    private bool _isSaveDialogOpen;

    public ProgrammableComputerFileManagerWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        UploadButton.OnPressed += _ => OnUploadPressed();
        NewFileButton.OnPressed += _ => OnNewFilePressed();
        DeleteButton.OnPressed += _ => OnDeletePressed();
        RefreshButton.OnPressed += _ => OnRefreshPressed();
        EditButton.OnPressed += _ => OnEditPressed();
        DownloadButton.OnPressed += _ => OnDownloadPressed();
        CloseButton.OnPressed += _ => Close();

        FileList.OnItemSelected += OnFileSelected;
        FileList.OnItemDeselected += OnFileDeselected;

    }

    public void SetupWindow(ComputerBoundUserInterfaceBase bui)
    {
        _bui = bui;
        UpdateFileList(null);
        _bui?.SendMessage(new ProgrammableComputerRequestFileListMessage());
    }

    public void UpdateFileList(ProgrammableComputerFileEntry[]? files)
    {
        FileList.Clear();
        _fileNames.Clear();
        _selectedIndex = -1;
        EditButton.Disabled = true;
        DownloadButton.Disabled = true;
        DeleteButton.Disabled = true;
        
        if (files == null)
            return;

        foreach (var file in files)
        {
            _fileNames.Add(file.Name);
            var sizeStr = file.Size < 1024
                ? $"{file.Size}B"
                : $"{file.Size / 1024.0f:F1}KB";
            FileList.AddItem($"{file.Name} ({sizeStr})");
        }
    }

    public void UpdateState(ProgrammableComputerBoundUserInterfaceState state)
    {
        UpdateFileList(state.Files);
    }

    private void OnFileSelected(ItemList.ItemListSelectedEventArgs args)
    {
        _selectedIndex = args.ItemIndex;
        EditButton.Disabled = false;
        DownloadButton.Disabled = false;
        DeleteButton.Disabled = false;
    }

    private void OnFileDeselected(ItemList.ItemListDeselectedEventArgs args)
    {
        _selectedIndex = -1;
        EditButton.Disabled = true;
        DownloadButton.Disabled = true;
        DeleteButton.Disabled = true;
    }

    private async void OnUploadPressed()
    {
        if (_isUploadDialogOpen)
            return;

        var filters = new FileDialogFilters(new FileDialogFilters.Group("lua", "txt"));
        _isUploadDialogOpen = true;
        await using var file = await _dialogs.OpenFile(filters, FileAccess.Read);
        _isUploadDialogOpen = false;

        if (Disposed || file == null)
            return;

        var fileName = file is FileStream stream
            ? Path.GetFileName(stream.Name)
            : $"upload-{DateTimeOffset.UtcNow.ToUnixTimeSeconds()}.lua";

        if (string.IsNullOrWhiteSpace(fileName))
            return;

        await using var memory = new MemoryStream();
        await file.CopyToAsync(memory);
        _bui?.SendMessage(new ProgrammableComputerUploadFileMessage(fileName, memory.ToArray()));
        _bui?.SendMessage(new ProgrammableComputerRequestFileListMessage());
    }

    private void OnNewFilePressed()
    {
        var fileName = $"/bin/untitled-{DateTimeOffset.UtcNow.ToUnixTimeSeconds()}.lua";
        _bui?.SendMessage(new ProgrammableComputerRunCommandMessage($"edit {QuoteShellArgument(fileName)}"));
    }

    private void OnDeletePressed()
    {
        var fileName = GetSelectedFileName();
        if (fileName != null)
        {
            _bui?.SendMessage(new ProgrammableComputerDeleteFileMessage(fileName));
            _bui?.SendMessage(new ProgrammableComputerRequestFileListMessage());
        }
    }

    private void OnEditPressed()
    {
        var fileName = GetSelectedFileName();
        if (fileName != null)
        {
            _bui?.SendMessage(new ProgrammableComputerRunCommandMessage($"edit {QuoteShellArgument(fileName)}"));
        }
    }

    private void OnDownloadPressed()
    {
        var fileName = GetSelectedFileName();
        if (fileName != null)
        {
            _pendingDownloadFileName = fileName;
            _bui?.SendMessage(new ProgrammableComputerDownloadFileMessage(fileName));
        }
    }

    private void OnRefreshPressed()
    {
        _bui?.SendMessage(new ProgrammableComputerRequestFileListMessage());
    }

    private string? GetSelectedFileName()
    {
        if (_selectedIndex < 0 || _selectedIndex >= _fileNames.Count)
            return null;

        return _fileNames[_selectedIndex];
    }

    private static string QuoteShellArgument(string value)
    {
        return '"' + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + '"';
    }

    public void ReceiveMessage(BoundUserInterfaceMessage message)
    {
        if (message is not ProgrammableComputerFileContentMessage contentMessage)
            return;

        _ = SaveDownloadedFile(contentMessage);
    }

    private async Task SaveDownloadedFile(ProgrammableComputerFileContentMessage message)
    {
        if (_isSaveDialogOpen)
            return;

        if (_pendingDownloadFileName != null && !string.Equals(_pendingDownloadFileName, message.FileName, StringComparison.Ordinal))
            return;

        _isSaveDialogOpen = true;
        try
        {
            var extension = Path.GetExtension(message.FileName).TrimStart('.');
            var filter = string.IsNullOrWhiteSpace(extension)
                ? null
                : new FileDialogFilters(new FileDialogFilters.Group(extension));

            var result = await _dialogs.SaveFile(filter);
            if (result == null)
                return;

            await result.Value.fileStream.WriteAsync(message.Content);
            await result.Value.fileStream.FlushAsync();
            await result.Value.fileStream.DisposeAsync();
        }
        finally
        {
            _pendingDownloadFileName = null;
            _isSaveDialogOpen = false;
        }
    }
}
