using System;
using System.IO;
using System.Numerics;
using System.Text.Json;
using System.Collections.Generic;
using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared.CCVar;
using Content.Shared.ProgrammableComputer;
using Robust.Client.Input;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Maths;
using Robust.Shared.Utility;
using Keyboard = Robust.Client.Input.Keyboard;

namespace Content.Client.ProgrammableComputer;

[GenerateTypedNameReferences]
public sealed partial class ProgrammableComputerWindow : FancyWindow, IComputerWindow<ProgrammableComputerBoundUserInterfaceState>
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly IInputManager _input = default!;
    private const string LockedPrefix = "[LOCKED]";
    private const string UnlockedPrefix = "[UNLOCKED]";

    private int BuildPackedKey(KeyEventArgs e, bool pressed, bool repeat)
    {
        var layoutCode = (_cfg.GetCVar(CCVars.ProgrammableComputerKeyboardLayout).ToLowerInvariant()) switch
        {
            "qwertz" => 1,
            "azerty" => 2,
            _ => 0,
        };
        return ((int)e.Key & 0x7F)
            | (pressed ? 1 << 7 : 0)
            | (repeat ? 1 << 8 : 0)
            | (e.Control ? 1 << 9 : 0)
            | (e.Alt ? 1 << 10 : 0)
            | (e.Shift ? 1 << 11 : 0)
            | (e.System ? 1 << 12 : 0)
            | (layoutCode << 13);
    }

    private ComputerBoundUserInterfaceBase? _bui;
    private EntityUid _owner;
    private bool _inputLocked;
    private string _baseTitle = string.Empty;
    private ProgrammableComputerDeviceWindow? _deviceWindow;
    private ProgrammableComputerFileManagerWindow? _fileWindow;
    private ProgrammableComputerBoundUserInterfaceState? _lastState;

    public ProgrammableComputerWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _baseTitle = Title ?? string.Empty;

        TerminalSurface.KeyboardFocusOnClick = true;
        TerminalSurface.OnTerminalClicked += OnTerminalClicked;
        TerminalSurface.OnCellPressed += OnTerminalCellPressed;
        _input.FirstChanceOnKeyEvent += OnFirstChanceKeyEvent;
        StartButton.OnPressed += _ => _bui?.SendMessage(new ProgrammableComputerPowerActionMessage(ProgrammableComputerPowerAction.Start));
        ShutdownButton.OnPressed += _ => _bui?.SendMessage(new ProgrammableComputerPowerActionMessage(ProgrammableComputerPowerAction.Shutdown));
        RebootButton.OnPressed += _ => _bui?.SendMessage(new ProgrammableComputerPowerActionMessage(ProgrammableComputerPowerAction.Reboot));
        DevicesButton.OnPressed += _ => ToggleDeviceWindow();
        FilesButton.OnPressed += _ => ToggleFileWindow();

        SetInputLocked(false);

        OnClose += () =>
        {
            SaveWindowSize();
            _input.FirstChanceOnKeyEvent -= OnFirstChanceKeyEvent;
            TerminalSurface.OnTerminalClicked -= OnTerminalClicked;
            TerminalSurface.OnCellPressed -= OnTerminalCellPressed;
            _deviceWindow = null;
            _fileWindow = null;
        };
    }

    public void SetupComputerWindow(ComputerBoundUserInterfaceBase cb)
    {
        _bui = cb;
        if (cb is BoundUserInterface bui)
        {
            _owner = bui.Owner;
            LoadWindowSize();
        }
        SetInputLocked(false);
    }

    private void ToggleDeviceWindow()
    {
        if (_deviceWindow == null || !_deviceWindow.IsOpen)
        {
            _deviceWindow = new ProgrammableComputerDeviceWindow();
            _deviceWindow.SetupWindow(_bui!);
            _deviceWindow.OpenCenteredRight();
            if (_lastState != null)
                _deviceWindow.UpdateState(_lastState);
            _bui?.SendMessage(new ProgrammableComputerRefreshStateMessage());
        }
        else
        {
            _deviceWindow.Close();
        }
    }

    public void UpdateState(ProgrammableComputerBoundUserInterfaceState state)
    {
        _lastState = state;
        TerminalSurface.UpdateTerminal(state.TerminalCells, state.Width, state.Height, state.CursorX, state.CursorY, state.CursorBlink);
        StartButton.Disabled = state.PoweredOn || state.Booting;
        ShutdownButton.Disabled = !state.PoweredOn;
        RebootButton.Disabled = !state.PoweredOn;
        PowerStateLabel.Text = state.Booting
            ? "Power: BOOTING"
            : state.PoweredOn
                ? "Power: ON"
                : "Power: OFF";

        _deviceWindow?.UpdateState(state);
        _fileWindow?.UpdateState(state);
    }

    public void ReceiveMessage(BoundUserInterfaceMessage message)
    {
        _fileWindow?.ReceiveMessage(message);
    }

    private void ToggleFileWindow()
    {
        if (_fileWindow == null || !_fileWindow.IsOpen)
        {
            _fileWindow = new ProgrammableComputerFileManagerWindow();
            _fileWindow.SetupWindow(_bui!);
            _fileWindow.OpenCenteredRight();
            if (_lastState != null)
                _fileWindow.UpdateState(_lastState);
            _bui?.SendMessage(new ProgrammableComputerRefreshStateMessage());
        }
        else
        {
            _fileWindow.Close();
        }
    }

    protected override void ExitedTree()
    {
        SetInputLocked(false);
        base.ExitedTree();
        _input.FirstChanceOnKeyEvent -= OnFirstChanceKeyEvent;
        TerminalSurface.OnTerminalClicked -= OnTerminalClicked;
        TerminalSurface.OnCellPressed -= OnTerminalCellPressed;
    }

    protected override void ControlFocusExited()
    {
        base.ControlFocusExited();
        SetInputLocked(false);
    }

    private void OnTerminalClicked()
    {
        SetInputLocked(true);
    }

    private void OnTerminalCellPressed(Vector2i cell)
    {
        if (_bui == null || (!_inputLocked && !TerminalSurface.HasKeyboardFocus()))
            return;

        _bui.SendMessage(new ProgrammableComputerTouchMessage(cell.X, cell.Y));
    }

    private void SetInputLocked(bool locked)
    {
        _inputLocked = locked;

        if (locked)
            TerminalSurface.GrabKeyboardFocus();
        else
            TerminalSurface.ReleaseKeyboardFocus();

        Title = locked ? $"{LockedPrefix} {_baseTitle}" : $"{UnlockedPrefix} {_baseTitle}";
    }

    private void OnFirstChanceKeyEvent(KeyEventArgs keyEvent, KeyEventType type)
    {
        if (_bui == null || (!_inputLocked && !TerminalSurface.HasKeyboardFocus()))
            return;

        if (type == KeyEventType.Down && keyEvent.Key == Keyboard.Key.Escape)
        {
            SetInputLocked(false);
            keyEvent.Handle();
            return;
        }

        switch (type)
        {
            case KeyEventType.Down:
                _bui.SendMessage(new ProgrammableComputerKeyMessage(BuildPackedKey(keyEvent, true, false)));
                break;
            case KeyEventType.Repeat:
                _bui.SendMessage(new ProgrammableComputerKeyMessage(BuildPackedKey(keyEvent, true, true)));
                break;
            case KeyEventType.Up:
                _bui.SendMessage(new ProgrammableComputerKeyMessage(BuildPackedKey(keyEvent, false, false)));
                break;
        }

        keyEvent.Handle();
    }

    private void LoadWindowSize()
    {
        try
        {
            var sizeData = LoadWindowSizes();
            var key = _owner.ToString();
            if (sizeData.TryGetValue(key, out var savedSize))
            {
                SetSize = new Vector2(savedSize.Width, savedSize.Height);
                return;
            }

            // Fall back to default size if set
            var defaultSizeStr = _cfg.GetCVar(CCVars.ProgrammableComputerDefaultWindowSize);
            if (!string.IsNullOrEmpty(defaultSizeStr) && defaultSizeStr.Contains(','))
            {
                var parts = defaultSizeStr.Split(',');
                if (float.TryParse(parts[0], out var width) && float.TryParse(parts[1], out var height))
                {
                    SetSize = new Vector2(width, height);
                }
            }
        }
        catch
        {
            // Silently fail if window size can't be loaded
        }
    }

    private void SaveWindowSize()
    {
        try
        {
            if (_owner == EntityUid.Invalid)
                return;

            var sizeData = LoadWindowSizes();
            var size = PixelSizeBox.Size;
            sizeData[_owner.ToString()] = new SizeData { Width = size.X, Height = size.Y };
            SaveWindowSizes(sizeData);
        }
        catch
        {
            // Silently fail if window size can't be saved
        }
    }

    private static Dictionary<string, SizeData> LoadWindowSizes()
    {
        var settingsPath = GetWindowSizesPath();
        if (!File.Exists(settingsPath))
            return new Dictionary<string, SizeData>();

        try
        {
            var json = File.ReadAllText(settingsPath);
            var dict = JsonSerializer.Deserialize<Dictionary<string, SizeData>>(json);
            return dict ?? new Dictionary<string, SizeData>();
        }
        catch
        {
            return new Dictionary<string, SizeData>();
        }
    }

    private static void SaveWindowSizes(Dictionary<string, SizeData> sizeData)
    {
        var settingsPath = GetWindowSizesPath();
        var dir = Path.GetDirectoryName(settingsPath);
        if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
            Directory.CreateDirectory(dir);

        var json = JsonSerializer.Serialize(sizeData, new JsonSerializerOptions { WriteIndented = true });
        File.WriteAllText(settingsPath, json);
    }

    private static string GetWindowSizesPath()
    {
        var baseDir = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
        return Path.Combine(baseDir, "SpaceStation14", "programmable_computer_window_sizes.json");
    }

    private record SizeData
    {
        public float Width { get; set; }
        public float Height { get; set; }
    }
}
