using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared.CCVar;
using Content.Shared.ProgrammableComputer;
using Robust.Client.Input;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Keyboard = Robust.Client.Input.Keyboard;

namespace Content.Client.ProgrammableComputer;

[GenerateTypedNameReferences]
public sealed partial class ProgrammableComputerWindow : FancyWindow, IComputerWindow<ProgrammableComputerBoundUserInterfaceState>
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly IInputManager _input = default!;
    private const string LockedPrefix = "[LOCKED]";
    private const string UnlockedPrefix = "[UNLOCKED]";

    private int BuildPackedKey(KeyEventArgs e, bool pressed, bool repeat)
    {
        var layoutCode = (_cfg.GetCVar(CCVars.ProgrammableComputerKeyboardLayout).ToLowerInvariant()) switch
        {
            "qwertz" => 1,
            "azerty" => 2,
            _        => 0,
        };
        return ((int) e.Key & 0x7F)
            | (pressed  ? 1 << 7  : 0)
            | (repeat   ? 1 << 8  : 0)
            | (e.Control ? 1 << 9  : 0)
            | (e.Alt     ? 1 << 10 : 0)
            | (e.Shift   ? 1 << 11 : 0)
            | (e.System  ? 1 << 12 : 0)
            | (layoutCode << 13);
    }

    private ComputerBoundUserInterfaceBase? _bui;
    private bool _inputLocked;
    private string _baseTitle = string.Empty;

    public ProgrammableComputerWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _baseTitle = Title ?? string.Empty;

        TerminalSurface.KeyboardFocusOnClick = true;
        TerminalSurface.OnTerminalClicked += OnTerminalClicked;
        _input.FirstChanceOnKeyEvent += OnFirstChanceKeyEvent;
        StartButton.OnPressed += _ => _bui?.SendMessage(new ProgrammableComputerPowerActionMessage(ProgrammableComputerPowerAction.Start));
        ShutdownButton.OnPressed += _ => _bui?.SendMessage(new ProgrammableComputerPowerActionMessage(ProgrammableComputerPowerAction.Shutdown));
        RebootButton.OnPressed += _ => _bui?.SendMessage(new ProgrammableComputerPowerActionMessage(ProgrammableComputerPowerAction.Reboot));

        SetInputLocked(false);

        OnClose += () =>
        {
            _input.FirstChanceOnKeyEvent -= OnFirstChanceKeyEvent;
            TerminalSurface.OnTerminalClicked -= OnTerminalClicked;
        };
    }

    public void SetupComputerWindow(ComputerBoundUserInterfaceBase cb)
    {
        _bui = cb;
        SetInputLocked(false);
    }

    public void UpdateState(ProgrammableComputerBoundUserInterfaceState state)
    {
        TerminalSurface.UpdateTerminal(state.TerminalCells, state.CursorX, state.CursorY, state.CursorBlink);
        StartButton.Disabled = state.PoweredOn || state.Booting;
        ShutdownButton.Disabled = !state.PoweredOn;
        RebootButton.Disabled = !state.PoweredOn;
        PowerStateLabel.Text = state.Booting
            ? "Power: BOOTING"
            : state.PoweredOn
                ? "Power: ON"
                : "Power: OFF";
    }

    protected override void ExitedTree()
    {
        SetInputLocked(false);
        base.ExitedTree();
        _input.FirstChanceOnKeyEvent -= OnFirstChanceKeyEvent;
        TerminalSurface.OnTerminalClicked -= OnTerminalClicked;
    }

    protected override void ControlFocusExited()
    {
        base.ControlFocusExited();
        SetInputLocked(false);
    }

    private void OnTerminalClicked()
    {
        SetInputLocked(true);
    }

    private void SetInputLocked(bool locked)
    {
        _inputLocked = locked;

        if (locked)
            TerminalSurface.GrabKeyboardFocus();
        else
            TerminalSurface.ReleaseKeyboardFocus();

        Title = locked ? $"{LockedPrefix} {_baseTitle}" : $"{UnlockedPrefix} {_baseTitle}";
    }

    private void OnFirstChanceKeyEvent(KeyEventArgs keyEvent, KeyEventType type)
    {
        if (_bui == null || (!_inputLocked && !TerminalSurface.HasKeyboardFocus()))
            return;

        if (type == KeyEventType.Down && keyEvent.Key == Keyboard.Key.Escape)
        {
            SetInputLocked(false);
            keyEvent.Handle();
            return;
        }

        switch (type)
        {
            case KeyEventType.Down:
                _bui.SendMessage(new ProgrammableComputerKeyMessage(BuildPackedKey(keyEvent, true,  false)));
                break;
            case KeyEventType.Repeat:
                _bui.SendMessage(new ProgrammableComputerKeyMessage(BuildPackedKey(keyEvent, true,  true)));
                break;
            case KeyEventType.Up:
                _bui.SendMessage(new ProgrammableComputerKeyMessage(BuildPackedKey(keyEvent, false, false)));
                break;
        }

        keyEvent.Handle();
    }
}
